### PR TITLE
first draft at a working stingray-accounts-service

### PR DESCRIPTION
**Pull request by davidmdm**

### CODE REVIEW

**Comment by davidmdm** [comment]
@mlaflamm NOT FOR MERGING JUST LOOKING

**Comment by mlaflamm** [comment]
:star: PR built and available in a preview environment **lvlstudio-stingray-pr-1** [here](http://stingray.jx-lvlstudio-stingray-pr-1.e2-dev.com)

**Comment by mlaflamm** [comment]
:star: PR built and available in a preview environment **lvlstudio-stingray-pr-1** [here](http://stingray.jx-lvlstudio-stingray-pr-1.e2-dev.com)

**Comment by mlaflamm** [comment]
:star: PR built and available in a preview environment **lvlstudio-stingray-pr-1** [here](http://stingray.jx-lvlstudio-stingray-pr-1.e2-dev.com)

**Comment by mlaflamm** [comment]
:star: PR built and available in a preview environment **lvlstudio-stingray-pr-1** [here](http://stingray.jx-lvlstudio-stingray-pr-1.e2-dev.com)

**Comment by mlaflamm** [comment]
:star: PR built and available in a preview environment **lvlstudio-stingray-pr-1** [here](http://stingray.jx-lvlstudio-stingray-pr-1.e2-dev.com)

**Comment by mlaflamm** [comment]
:star: PR built and available in a preview environment **lvlstudio-stingray-pr-1** [here](http://stingray.jx-lvlstudio-stingray-pr-1.e2-dev.com)

**Comment by mlaflamm** [comment]
:star: PR built and available in a preview environment **lvlstudio-stingray-pr-1** [here](http://stingray.jx-lvlstudio-stingray-pr-1.e2-dev.com)

**Pull request merged**
